repos:
  - go-utils
  - keptn
  - examples
  - spec
  - integrations
  - kubernetes-utils
  - helm-charts
  - helm-charts-dev
  - get.keptn.sh
  - gh-automation
  - dns.keptn.sh

approvers: []

maintainers:
  - grabnerandi
  - bacherfl
  - laneli
  - oleg-nenashev
  - ermin-muratovic
  - agrimmer
  - Kirdock
  - bradmccoydev
  - thschue
  - christian-kreuzberger-dtx
  - warber
  - RealAnna
  - odubajDT
  - AloisReitbauer
  - johannes-b
  - jetzlstorfer
  - DavidPHirsch

admins: []
